### ISSUE TITLE
Review vignette hyperSpec.Rmd

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#195]
This issue is for the discussion of the current review round for `hyperSpec.Rmd` vignette. You **should edit** this my message to add/remove tasks.

I recommend addressing these issues:

- [x] Either Appendix 1 should be removed in favor of the "Reference" section in **pkgdown** website or deprecated functions (e.g., `scan.*`) should not be mentioned at all in that part.

    ![image](https://user-images.githubusercontent.com/12725868/85406278-3c3ccd80-b56a-11ea-88b4-7f0e2e57c7ae.png)
- [x] Address _Vignette Style Standards_ in [CONTRIBUTING.md](https://github.com/cbeleites/hyperSpec/blob/develop/CONTRIBUTING.md#vignette-style-and-standards) _This is an ongoing task but once the revision of this vignette is complete we will probably have the vast majority of standards that we will need._

- [x] Also for  _Vignette Style Standards_ we need to select a consistent color scheme for this vignette which will become the standard across all vignettes.  We need at least a qualitative palette for plotting spectra individually or by groups, plus a palette that will work well in maps.  Let me make a strong pitch for color-blind-safe choices: in my teaching career I ran into color blind students regularly and if you don't plan for this, you completely disable their ability to use the materials you give them.  There is a good discussion and suggestions [here](https://blog.datawrapper.de/colorblindness-part2/ ).  [My Suggestion](https://projects.susielu.com/viz-palette?colors=[%22#000000%22,%22#084A96%22,%22#7490e7%22,%22#B4BAEA%22,%22#ff6a6a%22,%22#CFB93D%22,%22#FAE159%22]&backgroundColor=%22white%22&fontColor=%22black%22&mode=%22normal%22)

- [x] When #177 is completed there are changes to be made in `hyperSpec.Rmd` When 177 is changed this vignette will error so the person completing 177 should fix.  Closing here.

- [x] `intro--structure--hyperSpec--objects.png` probably should have the color scheme done differently.  Who has the original? Changed in https://github.com/cbeleites/hyperSpec/commit/0bbfbd2173c48041138716f014199f8aca37508d

- [x] Remove use of `\mFun` (marginal mention of functions, does not apply to html documents but does no harm,  other than cluttering) DECIDED TO KEEP FOR NOW

- [x] Remove use of `\index` as html pages can be searched in the browser. DECIDED TO KEEP FOR NOW

- [x] The bibliography (for all vigs) is constructed in a rather complex way. Can we just use a standard `.bib` file across all vigs? (#220, #221) These other issues will resolve.

- [x] There is a problem with the plot of the dendrogram example; we need to pass something to reduce the size of the labels if possible (search for "dendrogram").  Added some arguments to improve the appearance of the plot.

- [x] Bryan added infrastructure to streamline referring to other vignettes.  This can be used in all vignettes and can be readily extended by modify `about-vignettes.Rmd`, for instance links to each vig on pkgdown could be added.  See https://github.com/cbeleites/hyperSpec/commit/157fd6596b396f8e185ebcf8e58f7cded44711cf

- [x] There is some inconsistency in the use of `fig.width`  Review. Fixed with https://github.com/cbeleites/hyperSpec/commit/1e4307edde51d3e321c12257743ce6cb083aa84d

**Comment by GegznaV** [comment]
>` intro--structure--hyperSpec--objects.png` probably should have the color scheme done differently. Who has the original?

@bryanhanson, it was generated with LaTeX code, so the source is in `hyperSpec.Rnw`


***

> Remove use of `\mFun` [...]

> Remove use of `\index` [...] 

> The bibliography (for all vigs) is constructed in a rather complex way. Can we just use a standard .bib file across all vigs?

Can we leave these questions untouched until I return after vocation (in mid July)?

**Comment by bryanhanson** [comment]
@GegznaV thanks for the pointer to the `.Rnw`  We will not act on those other items until you return!

**Comment by GegznaV** [comment]
Thoughts on:

> infrastructure to streamline referring to other vignettes.  [...]

I do not find it convenient to read online documentation that suggests opening local documentation in R while the same material is available online. 
I read that it is possible to have direct links in HTML vignettes to other vignettes in both R documentation and `pkgdown` @bryanhanson  Could you investigate these possibilities while I am away?

**Comment by bryanhanson** [comment]
I think in the long run we need both: links to local documentation because some people may be offline (at times), and direct links to pkgdown or other versions (which right now are all `hyperSpec` vignettes but eventually some of these vignettes will be in `hyS.X` packages and hence one is linking "out" of the main package).  The  infrastructure I put in there allows us to change things in one file that is then propagated to all other vignettes.

**Comment by bryanhanson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Color scheme for vignettes](https://trello.com/c/iZpqr7cn/105-color-scheme-for-vignettes)

**Comment by GegznaV** [comment]
@bryanhanson 

> - Remove use of `\mFun` (marginal mention of functions, does not apply to html documents but does no harm, other than cluttering)
> - Remove use of `\index` as html pages can be searched in the browser.

As **hyperSpec** is going to be split into several packages, the documentation of different parts of **hyperSpec** functionality is also going to be scattered around different places. In the long run, I would like to have a separate repo for documentation in a form of, e.g., **bokdown**'s book, which is based on the same Rmd files as vignettes are and which is updated automatically, when the Rmd vignettes are updated in either of `r-hyperspec` packages. 
Bookdown allows creating several book formats including Gitbook and PDF book. Thus, I'd prefer keeping `\mFun` and `\index` tags as they might be useful for books in PDF.

But if we decide, that we do not want PDF to be built as a form of documentation, we can get rid of the tags.

**Comment by bryanhanson** [comment]
In that case, we'll leave them in there.  Also note that someone will need to go through and check that these functions are in the right places, as during the major overhaul I did not add any new entries.  I will mark the check list above accordingly.

**Comment by GegznaV** [comment]
> There is some inconsistency in the use of `fig.width`  Review.

@bryanhanson,  do you talk about `hyperSpec.Rmd` only?

I think, that in most places the default width should be used (i.e., no `fig.width`). Otherwise `fig.width = 7` could be used. In case wider figures are needed, additional option `out.width` (e.g., `out.width = "100%"`) should be used in order to fit the figure into the appropriate width on HTLM website.

**Comment by GegznaV** [comment]
> The bibliography (for all vigs) is constructed in a rather complex way. Can we just use a standard .bib file across all vigs?

@bryanhanson What do you not like about this system in particular? 

I translated it from Claudia's Rnw version. I also intended to do something in a less complex way but this version automatically updates the versions of packages. Especially, there were specific issues solved that are related to base R packages.

**Comment by bryanhanson** [comment]
On the figure widths, yes, I am referring to `hyperSpec.Rmd` only.  Anything that is a spectrum or spectra-like looks good full width.  For the maps, these seem better to be roughly square.  That's my opinion but of course we can do it any way people want.  If there's no strong feeling, that's how I'll do it in the next few days.  Clearly can be changed in the future.

**Comment by GegznaV** [comment]
My concern was that if the images in vignettes were too large, the package could take much space when installed.

@bryanhanson, if you want to change figure sizes, I recommend creating parameterization for a type of figure (intensity-vs-wavelength/time/depth type spectrum, map. etc.)  and not hard-coding the size for each individual figure (except some special cases). You should also apply the same figure-width related changes for `plotting.Rmd` and other vignettes.

**Comment by bryanhanson** [comment]
Good idea to parameterize.  I will do it that way.

**Comment by GegznaV** [comment]
For regular spectra, the default parameters may apply (i.e., no explicit `fig.width` in the options of individual chunk). Form maps, etc., different set of parameters may apply.

**Comment by GegznaV** [comment]
> I will do it that way.

Thanks 👍

**Comment by cbeleites** [comment]
> The bibliography (for all vigs) is constructed in a rather complex way. Can we just use a standard .bib file across all vigs?

I'd like to keep the possibility to use auto-generated bibliography from the package citations. For now I also decided to keep the possibility to give all the citations a package lists, as opposed to only one as is the standard **knitr** philosophy, see [here](https://github.com/yihui/knitr/issues/1089) and [here](https://github.com/yihui/knitr/issues/1733).

We can

- have temporary `.bib` files that are auto-generated to cite packages, and
- in addition a permanent `.bib` file for any further citations that we want to give. The easiest approach would be to rename `fileio.bib` into `hyperSpec.bib`, but since no other vignette has other citiations so far I think we can leave things as they are for now. The more so as fileio will need to be adapted to **hySpc.read.\***.
