### ISSUE TITLE
Strategy and plan to split hyperSpec into separate packages

### ISSUE THREAD

**Issue by GegznaV** [cbeleites/hyperSpec#214]
What should be done in order to start moving functions from **hyperSpec** into other packages? i.e.,

- should we solve any licensing issue to use MIT?
- should we decide on how large files will be managed (I was told that `drat` strategy is going to be used)
- [ ] unit tests should cover as many lines of code as possible to notice some discrepancies as early as possible (related #207)
- [x] rename some functions, etc. to have more consistency in code style (#208)
- [x] decide on the vision of necessary packages and repos (https://github.com/r-hyperspec/r-hyperspec.github.io/issues/5)
- some other issues?

***

**UPDATE:**

What is the strategy?

1. copy the code of the function to a destination package.
2. in **hyperSpec**, the function should be properly deprecated:
      - function `.Defunct()`  should be used when a function is totally removed from the package.
                 * **NOTE:** I see the issue if the function with the same name is in two packages of **hyperSpec** family.
                 * **Idea:** maybe we should add appropriate information in package startup message?
    - above the function's `roxygen2` documentation, add note `# FIXME: the function was removed from hyperSpec`  should be added.
    - in the `roxygen2` documentation, two additional concepts should be added:
           - `#' @concept removed from hyperSpec`
           - `#' @concept package ` [*name of package*] – the name of the package in which the new code will live.

**Comment by GegznaV** [comment]
Related: https://docs.google.com/spreadsheets/d/1johHVvxByZXhZD8DcYnqUeXf4ZLAigjMaEwvkzCQMh0/edit#gid=0

**Comment by eoduniyi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Project proposal & hyperSpec ecosystem](https://trello.com/c/rKYIP5lt/7-project-proposal-hyperspec-ecosystem)

**Comment by GegznaV** [comment]
I updated the strategy in the way I understood it. But I see some issues with that. So I think, we should discuss the process on the next Monday's meeting.

**Comment by GegznaV** [comment]
This issue was a call for discussion so I'm closing it now.
